package com.viesis.viescraft.api;

import net.minecraft.client.gui.GuiButton;

public class GuiVC {
	
	/** CheckMark 1 */
	public static GuiButton buttonC1;
	/** CheckMark 2 */
	public static GuiButton buttonC2;
	/** CheckMark 3 */
	public static GuiButton buttonC3;
	/** CheckMark 4 */
	public static GuiButton buttonC4;
	
	/** Main Menu */
	public static GuiButton buttonMM1;
	/** Upgrade */
	public static GuiButton buttonMM2;
	/** Visual */
	public static GuiButton buttonMM3;
	/** Module */
	public static GuiButton buttonMM4;
	/** Redstone */
	public static GuiButton buttonMM5;
	
	
	/** Choose Music */
	public static GuiButton buttonM5;
	/** Play Music */
	public static GuiButton buttonM6;
	/** Stop Music */
	public static GuiButton buttonM7;
	/** Play Random */
	public static GuiButton buttonM8;
	
	/** Done/Accept/Exit */
	public static GuiButton button501;
	/** Reset Appearance */
	public static GuiButton button502;
	/** Next */
	public static GuiButton button503;
	/** Prev */
	public static GuiButton button504;
	/** Back */
	public static GuiButton button505;
	/** Transparent Appearance */
	public static GuiButton button506;
	/** Transparent Appearance */
	public static GuiButton button507;
	
	/** Red Color */
	public static GuiButton buttonRed;
	/** Green Color */
	public static GuiButton buttonGreen;
	/** Blue Color */
	public static GuiButton buttonBlue;
	/** Remove Color */
	public static GuiButton buttonRemoveColor;
	
	/** Core 1 */
	public static GuiButton buttonCore1;
	/** Core 2 */
	public static GuiButton buttonCore2;
	/** Core 3 */
	public static GuiButton buttonCore3;
	/** Frame 1 */
	public static GuiButton buttonFrame1;
	/** Frame 2 */
	public static GuiButton buttonFrame2;
	/** Frame 3 */
	public static GuiButton buttonFrame3;
	/** Engine 1 */
	public static GuiButton buttonEngine1;
	/** Engine 2 */
	public static GuiButton buttonEngine2;
	/** Engine 3 */
	public static GuiButton buttonEngine3;
	/** Balloon 1 */
	public static GuiButton buttonBalloon1;
	/** Balloon 2 */
	public static GuiButton buttonBalloon2;
	/** Balloon 3 */
	public static GuiButton buttonBalloon3;
	
	/** Module Learn */
	public static GuiButton buttonModuleLearn;

	/** Module Reset */
	public static GuiButton buttonModuleReset;
	
	public static GuiButton buttonArmed;
	
	/** Tier 1 */
	public static GuiButton buttonT1;
	/** Tier 2 */
	public static GuiButton buttonT2;
	/** Tier 3 */
	public static GuiButton buttonT3;
	/** Tier 4 */
	public static GuiButton buttonT4;
	/** Tier 5 */
	public static GuiButton buttonT5;
	
	
	
	/** Record 11 */
	public static GuiButton buttonR01;
	/** Record 13 */
	public static GuiButton buttonR02;
	/** Record Blocks */
	public static GuiButton buttonR03;
	/** Record Mellohi */
	public static GuiButton buttonR04;
	/** Record Cat */
	public static GuiButton buttonR05;
	/** Record Stal */
	public static GuiButton buttonR06;
	
	/** Record Strad */
	public static GuiButton buttonR07;
	/** Record Chirp */
	public static GuiButton buttonR08;
	/** Record Far */
	public static GuiButton buttonR09;
	/** Record Mall */
	public static GuiButton buttonR10;
	/** Record Wait */
	public static GuiButton buttonR11;
	/** Record Ward */
	public static GuiButton buttonR12;
	
	/** Record Trigun */
	public static GuiButton buttonR13;
	/** Record Bramble */
	public static GuiButton buttonR14;
	/** Record Storms */
	public static GuiButton buttonR15;
	/** Record Cowboy */
	public static GuiButton buttonR16;
	/** Record Seagulls */
	public static GuiButton buttonR17;
	/** Record Seagulls */
	public static GuiButton buttonR18;
	
	

	public static GuiButton buttonModuleLesserAltitude;
	public static GuiButton buttonModuleNormalAltitude;
	public static GuiButton buttonModuleGreaterAltitude;
	

	public static GuiButton buttonModuleLesserSpeed;
	public static GuiButton buttonModuleNormalSpeed;
	public static GuiButton buttonModuleGreaterSpeed;

	public static GuiButton buttonModuleLesserStorage;
	public static GuiButton buttonModuleNormalStorage;
	public static GuiButton buttonModuleGreaterStorage;

	public static GuiButton buttonModuleLesserFuel;
	public static GuiButton buttonModuleNormalFuel;
	public static GuiButton buttonModuleGreaterFuel;

	public static GuiButton buttonModuleLesserMusic;
	public static GuiButton buttonModuleNormalMusic;
	public static GuiButton buttonModuleGreaterMusic;

	public static GuiButton buttonModuleLesserCruise;
	public static GuiButton buttonModuleNormalCruise;
	public static GuiButton buttonModuleGreaterCruise;

	public static GuiButton buttonModuleLesserWater;
	public static GuiButton buttonModuleNormalWater;
	public static GuiButton buttonModuleGreaterWater;

	public static GuiButton buttonModuleLesserInfiniteFuel;
	public static GuiButton buttonModuleNormalInfiniteFuel;
	public static GuiButton buttonModuleGreaterInfiniteFuel;

	public static GuiButton buttonModuleLesserBomb;
	public static GuiButton buttonModuleNormalBomb;
	public static GuiButton buttonModuleGreaterBomb;
	
	
	
	//Generic buttons
	public static GuiButton button00;
	public static GuiButton button01;
	public static GuiButton button02;
	public static GuiButton button03;
	public static GuiButton button04;
	public static GuiButton button05;
	public static GuiButton button06;
	public static GuiButton button07;
	public static GuiButton button08;
	public static GuiButton button09;
	public static GuiButton button10;
	public static GuiButton button11;
	public static GuiButton button12;
	public static GuiButton button13;
	public static GuiButton button14;
	public static GuiButton button15;
	public static GuiButton button16;
	public static GuiButton button17;
	public static GuiButton button18;
	public static GuiButton button19;
	public static GuiButton button20;
	public static GuiButton button21;
	public static GuiButton button22;
	public static GuiButton button23;
	public static GuiButton button24;
	public static GuiButton button25;
	public static GuiButton button26;
	public static GuiButton button27;
	public static GuiButton button28;
	public static GuiButton button29;
	public static GuiButton button30;
	public static GuiButton button31;
	public static GuiButton button32;
	public static GuiButton button33;
	public static GuiButton button34;
	public static GuiButton button35;
	public static GuiButton button36;
	public static GuiButton button37;
	public static GuiButton button38;
	public static GuiButton button39;
	public static GuiButton button40;
	public static GuiButton button41;
	public static GuiButton button42;
	public static GuiButton button43;
	public static GuiButton button44;
	public static GuiButton button45;
	public static GuiButton button46;
	public static GuiButton button47;
	public static GuiButton button48;
	public static GuiButton button49;
	public static GuiButton button50;
	public static GuiButton button51;
	public static GuiButton button52;
	public static GuiButton button53;
	public static GuiButton button54;
	public static GuiButton button55;
	public static GuiButton button56;
	public static GuiButton button57;
	public static GuiButton button58;
	public static GuiButton button59;
	public static GuiButton button60;
	public static GuiButton button61;
	public static GuiButton button62;
	public static GuiButton button63;
	public static GuiButton button64;
	public static GuiButton button65;
	public static GuiButton button66;
	public static GuiButton button67;
	public static GuiButton button68;
	public static GuiButton button69;
	public static GuiButton button70;
	public static GuiButton button71;
	public static GuiButton button72;
	public static GuiButton button73;
	public static GuiButton button74;
	public static GuiButton button75;
	public static GuiButton button76;
	public static GuiButton button77;
	public static GuiButton button78;
	public static GuiButton button79;
	public static GuiButton button80;
	public static GuiButton button81;
	public static GuiButton button82;
	public static GuiButton button83;
	public static GuiButton button84;
	public static GuiButton button85;
	public static GuiButton button86;
	public static GuiButton button87;
	public static GuiButton button88;
	public static GuiButton button89;
	public static GuiButton button90;
	public static GuiButton button91;
	public static GuiButton button92;
	public static GuiButton button93;
	public static GuiButton button94;
	public static GuiButton button95;
	public static GuiButton button96;
	public static GuiButton button97;
	public static GuiButton button98;
	public static GuiButton button99;
	
	//Generic buttons
	public static GuiButton buttonA00;
	public static GuiButton buttonA01;
	public static GuiButton buttonA02;
	public static GuiButton buttonA03;
	public static GuiButton buttonA04;
	public static GuiButton buttonA05;
	public static GuiButton buttonA06;
	public static GuiButton buttonA07;
	public static GuiButton buttonA08;
	public static GuiButton buttonA09;
	public static GuiButton buttonA10;
	public static GuiButton buttonA11;
	public static GuiButton buttonA12;
	public static GuiButton buttonA13;
	public static GuiButton buttonA14;
	public static GuiButton buttonA15;
	public static GuiButton buttonA16;
	public static GuiButton buttonA17;
	public static GuiButton buttonA18;
	public static GuiButton buttonA19;
	public static GuiButton buttonA20;
	public static GuiButton buttonA21;
	public static GuiButton buttonA22;
	public static GuiButton buttonA23;
	public static GuiButton buttonA24;
	public static GuiButton buttonA25;
	public static GuiButton buttonA26;
	public static GuiButton buttonA27;
	public static GuiButton buttonA28;
	public static GuiButton buttonA29;
	public static GuiButton buttonA30;
	public static GuiButton buttonA31;
	public static GuiButton buttonA32;
	public static GuiButton buttonA33;
	public static GuiButton buttonA34;
	public static GuiButton buttonA35;
	public static GuiButton buttonA36;
	public static GuiButton buttonA37;
	public static GuiButton buttonA38;
	public static GuiButton buttonA39;
	public static GuiButton buttonA40;
	public static GuiButton buttonA41;
	public static GuiButton buttonA42;
	public static GuiButton buttonA43;
	public static GuiButton buttonA44;
	public static GuiButton buttonA45;
	public static GuiButton buttonA46;
	public static GuiButton buttonA47;
	public static GuiButton buttonA48;
	public static GuiButton buttonA49;
	public static GuiButton buttonA50;
	public static GuiButton buttonA51;
	public static GuiButton buttonA52;
	public static GuiButton buttonA53;
	public static GuiButton buttonA54;
	public static GuiButton buttonA55;
	public static GuiButton buttonA56;
	public static GuiButton buttonA57;
	public static GuiButton buttonA58;
	public static GuiButton buttonA59;
	public static GuiButton buttonA60;
	public static GuiButton buttonA61;
	public static GuiButton buttonA62;
	public static GuiButton buttonA63;
	public static GuiButton buttonA64;
	public static GuiButton buttonA65;
	public static GuiButton buttonA66;
	public static GuiButton buttonA67;
	public static GuiButton buttonA68;
	public static GuiButton buttonA69;
	public static GuiButton buttonA70;
	public static GuiButton buttonA71;
	public static GuiButton buttonA72;
	public static GuiButton buttonA73;
	public static GuiButton buttonA74;
	public static GuiButton buttonA75;
	public static GuiButton buttonA76;
	public static GuiButton buttonA77;
	public static GuiButton buttonA78;
	public static GuiButton buttonA79;
	public static GuiButton buttonA80;
	public static GuiButton buttonA81;
	public static GuiButton buttonA82;
	public static GuiButton buttonA83;
	public static GuiButton buttonA84;
	public static GuiButton buttonA85;
	public static GuiButton buttonA86;
	public static GuiButton buttonA87;
	public static GuiButton buttonA88;
	public static GuiButton buttonA89;
	public static GuiButton buttonA90;
	public static GuiButton buttonA91;
	public static GuiButton buttonA92;
	public static GuiButton buttonA93;
	public static GuiButton buttonA94;
	public static GuiButton buttonA95;
	public static GuiButton buttonA96;
	public static GuiButton buttonA97;
	public static GuiButton buttonA98;
	public static GuiButton buttonA99;
	
	//Generic buttons
	public static GuiButton buttonB00;
	public static GuiButton buttonB01;
	public static GuiButton buttonB02;
	public static GuiButton buttonB03;
	public static GuiButton buttonB04;
	public static GuiButton buttonB05;
	public static GuiButton buttonB06;
	public static GuiButton buttonB07;
	public static GuiButton buttonB08;
	public static GuiButton buttonB09;
	public static GuiButton buttonB10;
	public static GuiButton buttonB11;
	public static GuiButton buttonB12;
	public static GuiButton buttonB13;
	public static GuiButton buttonB14;
	public static GuiButton buttonB15;
	public static GuiButton buttonB16;
	public static GuiButton buttonB17;
	public static GuiButton buttonB18;
	public static GuiButton buttonB19;
	public static GuiButton buttonB20;
	public static GuiButton buttonB21;
	public static GuiButton buttonB22;
	public static GuiButton buttonB23;
	public static GuiButton buttonB24;
	public static GuiButton buttonB25;
	public static GuiButton buttonB26;
	public static GuiButton buttonB27;
	public static GuiButton buttonB28;
	public static GuiButton buttonB29;
	public static GuiButton buttonB30;
	public static GuiButton buttonB31;
	public static GuiButton buttonB32;
	public static GuiButton buttonB33;
	public static GuiButton buttonB34;
	public static GuiButton buttonB35;
	public static GuiButton buttonB36;
	public static GuiButton buttonB37;
	public static GuiButton buttonB38;
	public static GuiButton buttonB39;
	public static GuiButton buttonB40;
	public static GuiButton buttonB41;
	public static GuiButton buttonB42;
	public static GuiButton buttonB43;
	public static GuiButton buttonB44;
	public static GuiButton buttonB45;
	public static GuiButton buttonB46;
	public static GuiButton buttonB47;
	public static GuiButton buttonB48;
	public static GuiButton buttonB49;
	public static GuiButton buttonB50;
	public static GuiButton buttonB51;
	public static GuiButton buttonB52;
	public static GuiButton buttonB53;
	public static GuiButton buttonB54;
	public static GuiButton buttonB55;
	public static GuiButton buttonB56;
	public static GuiButton buttonB57;
	public static GuiButton buttonB58;
	public static GuiButton buttonB59;
	public static GuiButton buttonB60;
	public static GuiButton buttonB61;
	public static GuiButton buttonB62;
	public static GuiButton buttonB63;
	public static GuiButton buttonB64;
	public static GuiButton buttonB65;
	public static GuiButton buttonB66;
	public static GuiButton buttonB67;
	public static GuiButton buttonB68;
	public static GuiButton buttonB69;
	public static GuiButton buttonB70;
	public static GuiButton buttonB71;
	public static GuiButton buttonB72;
	public static GuiButton buttonB73;
	public static GuiButton buttonB74;
	public static GuiButton buttonB75;
	public static GuiButton buttonB76;
	public static GuiButton buttonB77;
	public static GuiButton buttonB78;
	public static GuiButton buttonB79;
	public static GuiButton buttonB80;
	public static GuiButton buttonB81;
	public static GuiButton buttonB82;
	public static GuiButton buttonB83;
	public static GuiButton buttonB84;
	public static GuiButton buttonB85;
	public static GuiButton buttonB86;
	public static GuiButton buttonB87;
	public static GuiButton buttonB88;
	public static GuiButton buttonB89;
	public static GuiButton buttonB90;
	public static GuiButton buttonB91;
	public static GuiButton buttonB92;
	public static GuiButton buttonB93;
	public static GuiButton buttonB94;
	public static GuiButton buttonB95;
	public static GuiButton buttonB96;
	public static GuiButton buttonB97;
	public static GuiButton buttonB98;
	public static GuiButton buttonB99;
	
	//Generic buttons
	public static GuiButton buttonC00;
	public static GuiButton buttonC01;
	public static GuiButton buttonC02;
	public static GuiButton buttonC03;
	public static GuiButton buttonC04;
	public static GuiButton buttonC05;
	public static GuiButton buttonC06;
	public static GuiButton buttonC07;
	public static GuiButton buttonC08;
	public static GuiButton buttonC09;
	public static GuiButton buttonC10;
	public static GuiButton buttonC11;
	public static GuiButton buttonC12;
	public static GuiButton buttonC13;
	public static GuiButton buttonC14;
	public static GuiButton buttonC15;
	public static GuiButton buttonC16;
	public static GuiButton buttonC17;
	public static GuiButton buttonC18;
	public static GuiButton buttonC19;
	public static GuiButton buttonC20;
	public static GuiButton buttonC21;
	public static GuiButton buttonC22;
	public static GuiButton buttonC23;
	public static GuiButton buttonC24;
	public static GuiButton buttonC25;
	public static GuiButton buttonC26;
	public static GuiButton buttonC27;
	public static GuiButton buttonC28;
	public static GuiButton buttonC29;
	public static GuiButton buttonC30;
	public static GuiButton buttonC31;
	public static GuiButton buttonC32;
	public static GuiButton buttonC33;
	public static GuiButton buttonC34;
	public static GuiButton buttonC35;
	public static GuiButton buttonC36;
	public static GuiButton buttonC37;
	public static GuiButton buttonC38;
	public static GuiButton buttonC39;
	public static GuiButton buttonC40;
	public static GuiButton buttonC41;
	public static GuiButton buttonC42;
	public static GuiButton buttonC43;
	public static GuiButton buttonC44;
	public static GuiButton buttonC45;
	public static GuiButton buttonC46;
	public static GuiButton buttonC47;
	public static GuiButton buttonC48;
	public static GuiButton buttonC49;
	public static GuiButton buttonC50;
	public static GuiButton buttonC51;
	public static GuiButton buttonC52;
	public static GuiButton buttonC53;
	public static GuiButton buttonC54;
	public static GuiButton buttonC55;
	public static GuiButton buttonC56;
	public static GuiButton buttonC57;
	public static GuiButton buttonC58;
	public static GuiButton buttonC59;
	public static GuiButton buttonC60;
	public static GuiButton buttonC61;
	public static GuiButton buttonC62;
	public static GuiButton buttonC63;
	public static GuiButton buttonC64;
	public static GuiButton buttonC65;
	public static GuiButton buttonC66;
	public static GuiButton buttonC67;
	public static GuiButton buttonC68;
	public static GuiButton buttonC69;
	public static GuiButton buttonC70;
	public static GuiButton buttonC71;
	public static GuiButton buttonC72;
	public static GuiButton buttonC73;
	public static GuiButton buttonC74;
	public static GuiButton buttonC75;
	public static GuiButton buttonC76;
	public static GuiButton buttonC77;
	public static GuiButton buttonC78;
	public static GuiButton buttonC79;
	public static GuiButton buttonC80;
	public static GuiButton buttonC81;
	public static GuiButton buttonC82;
	public static GuiButton buttonC83;
	public static GuiButton buttonC84;
	public static GuiButton buttonC85;
	public static GuiButton buttonC86;
	public static GuiButton buttonC87;
	public static GuiButton buttonC88;
	public static GuiButton buttonC89;
	public static GuiButton buttonC90;
	public static GuiButton buttonC91;
	public static GuiButton buttonC92;
	public static GuiButton buttonC93;
	public static GuiButton buttonC94;
	public static GuiButton buttonC95;
	public static GuiButton buttonC96;
	public static GuiButton buttonC97;
	public static GuiButton buttonC98;
	public static GuiButton buttonC99;
	
	
	
	//Generic buttons mainly used for Holiday Display Symbols
	public static GuiButton buttonEDH01;
	public static GuiButton buttonEDH02;
	public static GuiButton buttonEDH03;
	public static GuiButton buttonEDH04;
	public static GuiButton buttonEDH05;
	public static GuiButton buttonEDH06;
	public static GuiButton buttonEDH07;
	public static GuiButton buttonEDH08;
	public static GuiButton buttonEDH09;
	public static GuiButton buttonEDH10;
	public static GuiButton buttonEDH11;
	public static GuiButton buttonEDH12;
	public static GuiButton buttonEDH13;
	public static GuiButton buttonEDH14;
	public static GuiButton buttonEDH15;
	public static GuiButton buttonEDH16;
	public static GuiButton buttonEDH17;
	public static GuiButton buttonEDH18;
	public static GuiButton buttonEDH19;
	public static GuiButton buttonEDH20;
	public static GuiButton buttonEDH21;
	public static GuiButton buttonEDH22;
	public static GuiButton buttonEDH23;
	public static GuiButton buttonEDH24;
	public static GuiButton buttonEDH25;
	public static GuiButton buttonEDH26;
	public static GuiButton buttonEDH27;
	public static GuiButton buttonEDH28;
	public static GuiButton buttonEDH29;
	public static GuiButton buttonEDH30;
	public static GuiButton buttonEDH31;
	public static GuiButton buttonEDH32;
	public static GuiButton buttonEDH33;
	public static GuiButton buttonEDH34;
	public static GuiButton buttonEDH35;
	public static GuiButton buttonEDH36;
	public static GuiButton buttonEDH37;
	public static GuiButton buttonEDH38;
	public static GuiButton buttonEDH39;
	public static GuiButton buttonEDH40;
	public static GuiButton buttonEDH41;
	public static GuiButton buttonEDH42;
	public static GuiButton buttonEDH43;
	public static GuiButton buttonEDH44;
	public static GuiButton buttonEDH45;
	public static GuiButton buttonEDH46;
	public static GuiButton buttonEDH47;
	public static GuiButton buttonEDH48;
	public static GuiButton buttonEDH49;
	public static GuiButton buttonEDH50;
	public static GuiButton buttonEDH51;
	public static GuiButton buttonEDH52;
	public static GuiButton buttonEDH53;
	public static GuiButton buttonEDH54;
	public static GuiButton buttonEDH55;
	public static GuiButton buttonEDH56;
	public static GuiButton buttonEDH57;
	public static GuiButton buttonEDH58;
	public static GuiButton buttonEDH59;
	public static GuiButton buttonEDH60;
	public static GuiButton buttonEDH61;
	public static GuiButton buttonEDH62;
	public static GuiButton buttonEDH63;
	public static GuiButton buttonEDH64;
	public static GuiButton buttonEDH65;
	public static GuiButton buttonEDH66;
	public static GuiButton buttonEDH67;
	public static GuiButton buttonEDH68;
	public static GuiButton buttonEDH69;
	public static GuiButton buttonEDH70;
	public static GuiButton buttonEDH71;
	public static GuiButton buttonEDH72;
	public static GuiButton buttonEDH73;
	public static GuiButton buttonEDH74;
	public static GuiButton buttonEDH75;
	public static GuiButton buttonEDH76;
	public static GuiButton buttonEDH77;
	public static GuiButton buttonEDH78;
	public static GuiButton buttonEDH79;
	public static GuiButton buttonEDH80;
	public static GuiButton buttonEDH81;
	public static GuiButton buttonEDH82;
	public static GuiButton buttonEDH83;
	public static GuiButton buttonEDH84;
	public static GuiButton buttonEDH85;
	public static GuiButton buttonEDH86;
	public static GuiButton buttonEDH87;
	public static GuiButton buttonEDH88;
	public static GuiButton buttonEDH89;
	public static GuiButton buttonEDH90;
	public static GuiButton buttonEDH91;
	public static GuiButton buttonEDH92;
	public static GuiButton buttonEDH93;
	public static GuiButton buttonEDH94;
	public static GuiButton buttonEDH95;
	public static GuiButton buttonEDH96;
	public static GuiButton buttonEDH97;
	public static GuiButton buttonEDH98;
	public static GuiButton buttonEDH99;
}
